//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bookera.Entity;

namespace Bookera.Data.Repository
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
    
	public partial class BookeraEntities : DbContext
	{
		public BookeraEntities()
			: base("name=BookeraEntities")
		{
		}
    
		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}
    
		public virtual DbSet<Author> Authors { get; set; }
		public virtual DbSet<AuthorBook> AuthorBooks { get; set; }
		public virtual DbSet<Book> Books { get; set; }
		public virtual DbSet<Country> Countries { get; set; }
		public virtual DbSet<Image> Images { get; set; }
		public virtual DbSet<Location> Locations { get; set; }
		public virtual DbSet<Member> Members { get; set; }
		public virtual DbSet<Publisher> Publishers { get; set; }
		public virtual DbSet<Reader> Readers { get; set; }
		public virtual DbSet<Status> Statuses { get; set; }
		public virtual DbSet<User> Users { get; set; }
	}
}
