//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
    	public Author()
    	{
    		this.AuthorBook = new HashSet<AuthorBook>();
    	}
    
    	public int AuthorId { get; set; }
    	public string FirstName { get; set; }
    	public string LastName { get; set; }
    	public string MiddleName { get; set; }
    	public Nullable<System.DateTime> DateOfBirth { get; set; }
    	public int BirthplaceId { get; set; }
    	public string Email { get; set; }
    	public string Website { get; set; }
    	public Nullable<int> LocationId { get; set; }
    
    	public virtual ICollection<AuthorBook> AuthorBook { get; set; }
    }
}
