//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorBook
    {
    	public long AuthorBookId { get; set; }
    	public int AuthorId { get; set; }
    	public long BookId { get; set; }
    	public int PublisherId { get; set; }
    
    	public virtual Author Author { get; set; }
    	public virtual Book Book { get; set; }
    	public virtual Publisher Publisher { get; set; }
    }
}
