//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
    	public Book()
    	{
    		this.AuthorBook = new HashSet<AuthorBook>();
    	}
    
    	public long BookId { get; set; }
    	public string Title { get; set; }
    	public string Annotation { get; set; }
    	public string ISBN { get; set; }
    	public System.DateTime PublicationDate { get; set; }
    	public int PageNumber { get; set; }
    	public int ImageId { get; set; }
    
    	public virtual ICollection<AuthorBook> AuthorBook { get; set; }
    	public virtual Image Image { get; set; }
    }
}
