//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
    	public Country()
    	{
    		this.Location = new HashSet<Location>();
    		this.Publisher = new HashSet<Publisher>();
    		this.Reader = new HashSet<Reader>();
    	}
    
    	public short CountryId { get; set; }
    	public string Name { get; set; }
    	public string Capital { get; set; }
    
    	public virtual ICollection<Location> Location { get; set; }
    	public virtual ICollection<Publisher> Publisher { get; set; }
    	public virtual ICollection<Reader> Reader { get; set; }
    }
}
