//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
    	public Image()
    	{
    		this.Book = new HashSet<Book>();
    	}
    
    	public int ImageId { get; set; }
    	public byte[] ImageData { get; set; }
    
    	public virtual ICollection<Book> Book { get; set; }
    }
}
