//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
    	public int MemberId { get; set; }
    	public int ReaderId { get; set; }
    	public int UserId { get; set; }
    
    	public virtual Reader Reader { get; set; }
    	public virtual User User { get; set; }
    }
}
