//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
    	public Publisher()
    	{
    		this.AuthorBook = new HashSet<AuthorBook>();
    	}
    
    	public int PublisherId { get; set; }
    	public string Name { get; set; }
    	public short CountryId { get; set; }
    	public string Address { get; set; }
    	public string Phone { get; set; }
    	public string Email { get; set; }
    	public string Website { get; set; }
    
    	public virtual ICollection<AuthorBook> AuthorBook { get; set; }
    	public virtual Country Country { get; set; }
    }
}
