//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
    	public Reader()
    	{
    		this.Member = new HashSet<Member>();
    	}
    
    	public int ReaderId { get; set; }
    	public string FirstName { get; set; }
    	public string LastName { get; set; }
    	public string MiddleName { get; set; }
    	public System.DateTime DateOfBirth { get; set; }
    	public short CountryId { get; set; }
    	public string Email { get; set; }
    	public int StatusId { get; set; }
    
    	public virtual Country Country { get; set; }
    	public virtual ICollection<Member> Member { get; set; }
    	public virtual Status Status { get; set; }
    }
}
