//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookera.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
    	public Status()
    	{
    		this.Reader = new HashSet<Reader>();
    	}
    
    	public int StatusId { get; set; }
    	public string Name { get; set; }
    
    	public virtual ICollection<Reader> Reader { get; set; }
    }
}
